config/routes.rb
Stationgrade::Application.routes.draw do
  resources :stops, :path => :stations, :only => [:show, :index] do
    resources :incidents, :only => [:new, :create, :show]
  end
  
  root :to => "home#index"
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  Kinds = %w{rat garbage}
  
  belongs_to :station, :inverse_of => :incidents

  validates :station, :presence => true
  validates :kind, :inclusion => { :in => Kinds }
  validates :happened_at, :presence => true
  
  def happened_at_display
    self.happened_at.strftime("%b %-d '%y %l:%M %P")
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, :presence => true
  
  has_many :station_routes
  has_many :stations, :through => :station_routes
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  
  has_many :incidents, :inverse_of => :station
  has_many :station_routes
  has_many :routes, :through => :station_routes
end

app/models/station_route.rb
class StationRoute < ActiveRecord::Base
  belongs_to :station
  belongs_to :route
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def geo_json_for(stops)
    {
      :type => "FeatureCollection",
      :features => stops.map(&:as_geo_json)
    }
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    respond_to do |format|
      format.html
      format.json do
        render :json => geo_json_for( Stop.station )
      end
    end
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  
  before_filter :load_stop_for_incident
  
  def show
    @incident = Incident.find params[:id]
  end
  
  def new
    @incident = @stop.incidents.build
  end
  
  def create
    if params[:incident][:kind].present? && params[:incident][:kind].length > 0
      params[:incident][:kind].each do |kind|
        Incident.create params[:incident].merge(:stop_id => @stop.id, :kind => kind)
      end
      respond_to do |format|
        format.html { redirect_to stop_path(@stop) }
        format.json { 
          render :json => { 
            :view => render_to_string(:partial => "stops/popup.html", :locals => { 
              :stop => @stop, :incidents => @stop.incidents, :incident => Incident.new(params[:incident]) 
            }) 
          }
        } 
      end
    else
      @incident = @stop.incidents.build params[:incident]
      
      respond_to do |format|
        flash[:alert] = "Hey, was it a rat or garbage?" 
        format.html { render :action => :new }
        format.json { 
          render :json => { 
            :view => render_to_string(:partial => "stops/popup.html", :locals => { 
              :stop => @stop, :incidents => @stop.incidents, :incident => @incident 
            }) 
          }
        }
      end
    end
  end
  
  private
  
  def load_stop_for_incident
    @stop = Stop.find params[:stop_id]
  end
  
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController

  def index
    @stops    = Stop.station
  end
  
  def show
    @stop      = Stop.find params[:id]
    @incidents = @stop.incidents
    
    respond_to do |format|
      format.html
      format.json {
        render :json => { 
          :view => render_to_string(:partial => "popup.html", :locals => { 
            :stop => @stop, :incidents => @incidents, :incident => @stop.incidents.build(:type => "rat") 
          }) 
        } 
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def line_icon_url(line)
    "http://travel.mtanyct.info/serviceadvisory/Images/#{line.downcase}_shad.jpg"
  end
end

app/views/home/index.html.erb
<div id="map"></div>

app/views/incidents/_form.html.erb
<%= form_for [stop, incident], :url => stop_incidents_url(stop) do |form| %>

  <ul>
    <li>
      <% for kind in Incident::Kinds %>
      <%= form.label :kind, 
        "<input value='#{kind}' id='incident_kind_#{kind}' name='incident[kind][]' type='checkbox' #{"checked" if kind=="rat"}> #{image_tag "#{kind}.png"} ".html_safe, 
        :value => kind %> 
      <% end %>
    </li>
    
    <li>
      <%= form.label :title, "Summary (optional)" %> <br>
      <%= form.text_field :title %>
    </li>
    
    <li>
      <%= form.label :description, "Details (optional)" %> <br>
      <%= form.text_area :description, :rows => 5, :cols => 10 %>
    </li>
    
    <li>
      <%= form.label :happened_at, "Time" %> <br>
      <%= form.datetime_select :happened_at, :ampm => true, :use_month_numbers => true, :end_year => Date.today.year %>
    </li>
    
    <li>
      <%= form.submit %>
    </li>
  </ul>
  
<% end %>

app/views/incidents/new.html.erb
<%= render "form", :incident => @incident, :stop => @stop %>

app/views/incidents/show.html.erb
<h2><%= link_to @stop.name, @stop %>: <%= @incident.title %></h2>

<%= content_tag :p, @incident.description if @incident.description.present? %>

<ul>
  <li>Occurred: <%= @incident.happened_at %></li>
  <li>Reported: <%= @incident.created_at %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RatMapper</title>
  
  <link rel="icon" 
        type="image/png" 
        href="<%= image_path 'favicon.png' %>">
  
  <%= stylesheet_link_tag "/leaflet/leaflet.css" %>
  <!--[if lte IE 8]><%= stylesheet_link_tag "/leaflet/leaflet.ie.css" %><![endif]-->
	<%= javascript_include_tag "/leaflet/leaflet.js" %>
	
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller.controller_name %>" class="<%= controller.action_name %>">

<div id="wrapper">
  <div id="header">
    <h1><%= link_to "RatMapper", root_path %></h1>
    <ul id="nav">
      <li><%= link_to "All Stations", stops_path %></li>
    </ul>
  </div>
  
  <div id="content">
    <%= yield %>
  </div>
  
  <div id="notices">
    <% content_tag :p, flash[:notice], :class => "notice" if flash[:notice].present? %>
    <% content_tag :p, flash[:alert], :class => "alert" if flash[:alert].present? %>
  </div>
</div>
</body>
</html>

app/views/stops/_popup.html.erb
<div id="popup_content">
  <h2>
    <%= image_tag line_icon_url(stop.line), :alt => "#{stop.line} Platform", :title => "#{stop.line} Platform" %>
    <%= stop.name %>
  </h2>

  <p>
    <%= link_to pluralize(incidents.count, "reported incident"), stop_path(stop) %>
  </p>

  <div class="new_incident">
    <a>Report a rat</a>
    <% if flash[:alert].present? %>
    <div class="new_incident_form" >
      <%= content_tag :p, flash[:alert], :class => "alert" %>
    <% else %>
    <div class="new_incident_form" style="display:none">
    <% end %>
      <%= render "incidents/form.html", :stop => stop, :incident => incident %>    
    </div>
  </div>  
</div>

app/views/stops/index.html.erb
<h2>Stations</h2>

<ul>
<% for station in @stops %>
  <li><%= link_to station.name, station %></li>
<% end %>
</ul>

app/views/stops/show.html.erb
<h2 style="background: transparent url('<%= line_icon_url(@stop.line) %>') no-repeat scroll top left;">
  <%= @stop.display_name %>
</h2>

<div id="map" data-lat="<%= @stop.lat %>" data-lon="<%= @stop.lon %>" data-label="<%= @stop.name %>"></div>

<h3>Reported Incidents</h3>
<strong><%= link_to "Report something", new_stop_incident_path(@stop) %></strong>

<ul>
<% for incident in @incidents %>
  <li class="<%= incident.kind %> <%= cycle("odd", "even") %>">
    <div class='img_wrap'>
      <%= image_tag "#{incident.kind}.png" %>      
    </div>
    
    <div>
      <strong>
        <%= incident.title.present? ? incident.title : incident.happened_at_display %>
      </strong>
    </div>


    <%= content_tag :span, "@#{incident.happened_at_display}", :class => "date" if incident.title.present? %>
    <%= content_tag :div, simple_format(incident.description), :class => "description" if incident.description.present? %>
  </li>
<% end %>
</ul>